name: Run Tests Manually

on:
  workflow_dispatch:
    inputs:
      titleCustom:
        description: Choose Class
        type: string
        required: false
        default: "Let's check it!"
      selectCustom:
        description: "Choose class"
        type: choice
        required: true
        options:
          - mvn test
          - mvn test -Dtest=LoginTest
          - mvn test -Dtest=MainPageTest
          - mvn test -Dtest=EditProfileBoundaryTest
          - mvn test -Dtest=EditProfileHappyPathTest
          - mvn test -Dtest=RegistrationHappyPathTest
          - mvn test -Dtest=RegistrationSadPathTest
          - mvn test -Dtest=FriendTest
        default: All Tests

jobs:
  RunTests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        class: ["tests.LoginTest", "tests.MainPageTest", "tests.RegistrationHappyPathTest", "tests.RegistrationSadPathTest", "api.FriendTest", "tests.EditProfileHappyPathTest", "tests.EditProfileBoundaryTest", "AllTests"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Maven test
        run: mvn test -Dtest=${{ github.event.inputs.selectCustom }}
        env:
          ENV_BROWSER_NAME: "CHROME"
      - name: Attach screenshots and reports from Chrome
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: manual-screenshots-and-report-Chrome-${{ github.run_id }}  # Уникальное имя с использованием идентификатора выполнения
          path: |
            screenshots
            target/surefire-reports/emailable-report.html
      - name: Allure Report with history for Chrome
        uses: simple-elf/allure-report-action@v1.9
        if: always()
        with:
          allure_results: target/allure-results
          allure_report: allure-report-chrome
          gh_pages: gh-pages
          allure_history: allure-history-chrome
      - name: Deploy report to GitHub Pages for Chrome
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history-chrome
